Dev/QConnect/src/screens/FirtRun/FirstRunNavigator.js
Dev/QConnect/src/screens/FirtRun/FirtRunScreen.js

Test commit sample project files

---

Dev/QConnect/src/components/StudentCard.js

This component represents each student card that will be visible on the attendance page along with the teacher main page. Each component has a profile picture, text representing the student's name, text representing the student's assignment, and the ability to perform some task on press which is intended for future implementations. 
Here is an example of creating the StudentCard component: 
<StudentCard
onPress = {() => {
//Some function
}}
profilePic = {picture}
studentName = "Zyad Elgohary" 
currentAssignment = "Al-Baqara Page 1-4"/>

StudentCard.js Pull Request 1

---

Dev/QConnect/package-lock.json
Dev/QConnect/src/model/reducers/classReducer.js
Dev/QConnect/src/screens/TeacherScreens/ClassTabs/ClassAttendanceScreen.js

You are now able to fully save, view, and update both current and old attendance sheets based on selected date! The only issue with my code is that it's complexity is high, since I had to use nested for loops to accomplish it (O(N^2)). We can worry about this when we have much higher data sets however. But for now, it should be fine. Feel free to poke holes at my code and tell me if there is anything I need to revise.

Completed the Attendance Screen

---

Dev/QConnect/src/model/reducers/classReducer.js

#32 Redux actions are failing under the new schema

Fixing issue #32 (REDUX ACTIONS ARE FAILING UNDER THE NEW SCHEMA)

---

Dev/QConnect/__tests__/__snapshots__/TeacherScreens.snapshot.test.js.snap
Dev/QConnect/src/screens/TeacherScreens/AddClass/AddClassScreen.js

Added a toggle to change image or icon on the teacher web page, but only created the placeholder for the change image UI page.

Added a Modal to add Class screen

---

Dev/QConnect/App.js
Dev/QConnect/__tests__/__snapshots__/TeacherScreens.snapshot.test.js.snap
Dev/QConnect/src/screens/Evaluation/EvaluationPage.js

Can someone check to see if there is a way to make the snapshot up to date with the change of the date picker? Every day it fails just because it is not expecting the new date in the snapshot.

Update SnapShot log for dates

---

Dev/QConnect/src/screens/Evaluation/EvaluationPage.js

there were some errors from last merge (undefined variables). 
- Fixed the errors
- Removed setting unnecessary state variables
- Exit evaluation page to previous page after submit
- nit: fixed property name to match camel notation spec.

Fixes + updates on evaluation page 

---

Dev/QConnect/__tests__/__snapshots__/TeacherScreens.snapshot.test.js.snap
Dev/QConnect/src/screens/TeacherScreens/ClassTabs/ClassAttendanceScreen.js
Dev/QConnect/src/screens/TeacherScreens/ClassTabs/ClassMainScreen.js
Dev/QConnect/src/screens/TeacherScreens/LeftNavPane.js
Dev/QConnect/src/screens/TeacherScreens/TeacherMenu.js

Fixed the following issues:
- Can't switch to another menu item from left drawer menu when app starts in main class screen #114
- Attendance sCreEN is Broken #109

Fixed broken screens when app launches directly into main screen

---

Dev/QConnect/App.js
Dev/QConnect/__tests__/TeacherScreens.snapshot.test.js
Dev/QConnect/__tests__/__snapshots__/TeacherScreens.snapshot.test.js.snap
Dev/QConnect/app.json
Dev/QConnect/config/strings.js
Dev/QConnect/src/components/TopBanner.js
Dev/QConnect/src/model/reducers/classReducer.js
Dev/QConnect/src/screens/FirstRun/TeacherWelcomeScreen.js
Dev/QConnect/src/screens/TeacherScreens/AddClass/AddClassScreen.js
Dev/QConnect/src/screens/TeacherScreens/ClassTabs/ClassAttendanceScreen.js
Dev/QConnect/src/screens/TeacherScreens/ClassTabs/ClassEditScreen.js
Dev/QConnect/src/screens/TeacherScreens/ClassTabs/ClassHeaderNavigator.js
Dev/QConnect/src/screens/TeacherScreens/ClassTabs/ClassMainScreen.js
Dev/QConnect/src/screens/TeacherScreens/LeftNavPane.js
Dev/QConnect/src/screens/TeacherScreens/TeacherProfile/TeacherProfileScreen.js
Dev/QConnect/src/screens/TeacherScreens/helpers/mapStateToCurrentClassProps.js

- Removed demo class
- Saved currentClassIndex in Redux and make all screens refer to it to know which class to load
- Fixed first run flow by having teacher welcome push to Add Class, and Add Class pushes to Edit Students
- Changed EditClass title to Edit Students (to be clearer what it does)
- Updated TopBanner component to fallback to current class's title if the title is not passed is as a param
- Updated Add_Class to modify currentClassIndex to newly added class
- Updated Save_Teacher_Info to dynamically set any set of teacher properties passed in (to accomodate either setting current class index, or name, phone number, etc..)

 Removed DemoClass + Fixed first run flow + screens header title 

---

Dev/QConnect/__tests__/__snapshots__/TeacherScreens.snapshot.test.js.snap
Dev/QConnect/package-lock.json
Dev/QConnect/src/screens/StudentProfile/StudentProfileScreen.js

+ formatted grade to single decimal double digit.
Before: 
After:

Student Profile Screen: Fixed text overlap in Android

---

Dev/QConnect/App.js
Dev/QConnect/src/screens/StudentProfile/StudentProfileScreen.js

Truncates assignment name, student name, and notes in student profile screen if they stretch longer than their affordances.
TODO: Need to do the same on the student card to cover other class screens. That requires more work and will follow post this week's beta release iA.

Handled truncating long texts in StudentProfileScreen

---

Dev/QConnect/.gitignore
Dev/QConnect/App.js
Dev/QConnect/amplify/.config/project-config.json
Dev/QConnect/amplify/backend/analytics/qconnect/parameters.json
Dev/QConnect/amplify/backend/analytics/qconnect/pinpoint-cloudformation-template.json
Dev/QConnect/amplify/backend/auth/cognitob1424da5/cognitob1424da5-cloudformation-template.yml
Dev/QConnect/amplify/backend/auth/cognitob1424da5/parameters.json
Dev/QConnect/amplify/backend/backend-config.json
Dev/QConnect/amplify/team-provider-info.json
Dev/QConnect/config/analyticsEvents.js
Dev/QConnect/package-lock.json
Dev/QConnect/package.json
Dev/QConnect/src/components/ImageSelectionModal.js
Dev/QConnect/src/components/ImageSelectionRow.js
Dev/QConnect/src/components/QcActionButton.js
Dev/QConnect/src/model/reducers/classReducer.js
Dev/QConnect/src/screens/Evaluation/EvaluationPage.js
Dev/QConnect/src/screens/FirstRun/FirstRunScreen.js
Dev/QConnect/src/screens/FirstRun/TeacherWelcomeScreen.js
Dev/QConnect/src/screens/QcParentScreen.js
Dev/QConnect/src/screens/StudentProfile/StudentProfileScreen.js
Dev/QConnect/src/screens/TeacherScreens/AddClass/AddClassScreen.js
Dev/QConnect/src/screens/TeacherScreens/ClassTabs/ClassAttendanceScreen.js
Dev/QConnect/src/screens/TeacherScreens/ClassTabs/ClassEditScreen.js
Dev/QConnect/src/screens/TeacherScreens/ClassTabs/ClassMainScreen.js
Dev/QConnect/src/screens/TeacherScreens/LeftNavPane.js
Dev/QConnect/src/screens/TeacherScreens/TeacherProfile/TeacherProfileScreen.js

- Configured AWS Amplify for analytics
- Sent the following events to analytics:
- Screen loaded [which screens]
- Buttons clicked ["which button, on which screen"]
- Actions dispatched ["which redux actions have been initiated"]
- Which avatar / image has been selected? on the modal or the highlighted images row? on which screen?

Hooked up AWS Amplify Analytics

---

Dev/QConnect/src/screens/Evaluation/EvaluationPage.js
Dev/QConnect/src/screens/FirstRun/FirstRunScreen.js

A couple of files were not saved before the last commit. Submitting these as well..

A couple of more changes missed from the last PR.

---

Dev/QConnect/__tests__/redux/TeacherReducers.js
Dev/QConnect/src/screens/Evaluation/EvaluationPage.js

The rating validation alerting logic was not properly functioning.
Fixed the issue + corresponding tests [[Tests did catch the failure.. good stuff :)]]

Fixed rating validation logic + tests

---

Dev/QConnect/package-lock.json
Dev/QConnect/src/screens/StudentProfile/AssignmentEvaluation.js
Dev/QConnect/src/screens/StudentProfile/StudentProfileScreen.js
Dev/QConnect/src/screens/TeacherScreens/ClassTabs/ClassHeaderNavigator.js

Fixed Two issues and added new screen

Student Profile Enhancer

---

Dev/QConnect/__tests__/__snapshots__/TeacherScreens.snapshot.test.js.snap
Dev/QConnect/config/strings.js
Dev/QConnect/src/screens/StudentProfile/AssignmentEvaluation.js
Dev/QConnect/src/screens/StudentProfile/StudentProfileScreen.js
Dev/QConnect/src/screens/TeacherScreens/TeacherProfile/TeacherProfileScreen.js

- Fixed missed merge conflicts
- The new assignmentEvaluation Screen always showed current assignment name (while it showed th grade and notes of a past assignment). Fixed it to show the proper assignment name
- Added assignment completion date to the new assignment evaluation screen.
- Changed the placeholder string "Write a note" on the past evaluation screen, since it is read only for that case. The new string is: "There are no additional notes provided"
- Invoke the new assignment evaluation card when user presses on any area within the past assignment card. (It was only invoked when user presses on the notes section, which was not very discoverable)

Prep for weekly release: Fixes and enhancements to the latest changes 

---

Dev/QConnect/src/components/StudentCard.js
Dev/QConnect/src/screens/FirstRun/TeacherWelcomeScreen.js
Dev/QConnect/src/screens/StudentProfile/StudentProfileScreen.js
Dev/QConnect/src/screens/TeacherScreens/TeacherProfile/TeacherProfileScreen.js

…screen
https://github.com/KhalidPM/YungDevz/issues/163
Swapped the order keyboardavoidingView and TouchableWithoutFeedback to fix the padding issue on keyboard
The PR diff shows a lot of changes, this is mostly because I did indentation fixing from vscode linter. No code change there. The only code change is changing the oder of the KeyboardAvoidingView and TouchableWithoutFeedback

Fix for Issue #163, #176 and #178 (keyboard padding, delete long student name, & Fix arabic assignment display)

---

Dev/QConnect/config/strings.js
Dev/QConnect/src/components/FlowLayout.js
Dev/QConnect/src/screens/Evaluation/EvaluationPage.js
Dev/QConnect/src/screens/StudentProfile/StudentProfileScreen.js

- Fixed multiple undefined errors existing in the StudentProfileScreen
- Added the ability to add custom improvement areas
- Added the ability to remove improvement areas

Fixed bugs & Added the ability to edit improvement areas

---

Dev/QConnect/src/components/FlowLayout.js
Dev/QConnect/src/screens/FirstRun/FirstRunScreen.js

- Changed color of ellipses to action button
- Removed Ellipses & Plus Sign in modal to reduce button clicks
- Fixed bug where multiple improvement areas are deleted when one is clicked

Fixed issues with custom improvement areas

---

Dev/QConnect/src/components/FlowLayout.js
Dev/QConnect/src/model/reducers/classReducer.js
Dev/QConnect/src/screens/FirstRun/TeacherWelcomeScreen.js
Dev/QConnect/src/screens/FirstScreenLoader/FirstScreenLoader.js
Dev/QConnect/src/screens/TeacherScreens/ClassTabs/ClassAttendanceScreen.js
Dev/QConnect/src/screens/TeacherScreens/ClassTabs/ClassEditScreen.js
Dev/QConnect/src/screens/TeacherScreens/SettingsScreen/creditsScreen.js
Dev/QConnect/src/screens/TeacherScreens/TeacherProfile/TeacherProfileScreen.js

-Fixed issues with DURATION from previous PR
-Latest Assignment now will appear on top of the assignment history list

Assignment History Update

---

Dev/QConnect/config/analyticsEvents.js
Dev/QConnect/src/model/actions/authActions.js
Dev/QConnect/src/model/reducers/auth.js
Dev/QConnect/src/screens/AuthenticationScreens/ButtonSubmit.js
Dev/QConnect/src/screens/AuthenticationScreens/LoginScreen.js
Dev/QConnect/src/screens/FirstRun/TeacherWelcomeScreen.js
Dev/QConnect/src/screens/FirstScreenLoader/FirstScreenLoader.js

FirstRunCompleted wasn't set correctly on login flow. This is fixed now by having it dispatched off a successful login.
I also added a number of events to capture different states of the auth flow

Fixed first run completed logic + added analytics to auth flows

---

Dev/QConnect/package-lock.json
Dev/QConnect/src/screens/StudentProfile/StudentProfileScreen.js

Last merge changed classId and studentId props to studentIndex and classIndex, which are no longer used in our schema, causing the studentProfileScreen to fail to load

 Fixed bad merge from last PR (StudentProfileScreen) 
